# OS specific variables
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

# Configure firewall first
- name: iptables | add Opscenter (8888) port
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8888 -j ACCEPT -m comment --comment "Opscenter and datastax-agent"

- name: iptables | add inter-node (7000, 7001, 7199) ports
  command: /sbin/iptables -I INPUT 2 -p tcp --match multiport --dports 7000,7001,7199 -j ACCEPT -m comment --comment "inter node communication"

- name: iptables | add client (9042, 9160) ports
  command: /sbin/iptables -I INPUT 3 -p tcp --match multiport --dports 9042,9160 -j ACCEPT -m comment --comment "client ports"


- file: path=/etc/dse/conf state=directory mode=0755 owner=cassandra group=cassandra

# Create keystore
- name: dse | create a keystore
  shell: >
    echo | keytool
    -genkey -keyalg RSA
    -storepass datastax
    -alias {{ansible_hostname}}
    -keystore /etc/dse/conf/.keystore
    -dname "cn=Datastax, ou=Datastax, o=Datastax, c=US"
  args:
    creates: /etc/dse/conf/.keystore

- file: path=/etc/dse/conf/.keystore mode=0600 owner=cassandra group=cassandra

# Export public certificate to use by other nodes
- name: dse | export public cert to use by other nodes
  shell: >
    keytool
    -export
    -storepass datastax
    -alias {{ansible_hostname}}
    -keystore /etc/dse/conf/.keystore
    -file /etc/dse/conf/{{ansible_hostname}}.crt
  args:
    creates: /etc/dse/conf/{{ansible_hostname}}.crt

- file: path=/etc/dse/conf/{{ansible_hostname}}.crt mode=0644 owner=cassandra group=cassandra

# Sync certs to other hosts
- name: dse | sync certs to other nodes
  shell: rsync -av -e "ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa.ansible" /etc/dse/conf/*crt root@{{item}}:/etc/dse/conf/
  with_items:
    - 192.168.100.101
    - 192.168.100.102
    - 192.168.100.103

# copy cert import to /tmp
- name: dse | copy cert import to /tmp
  copy: src=cert_import.sh dest=/tmp/cert_import.sh mode=0755

# Import certifactes to truststore
- name: dse | import certs to a truststore
  shell: sh /tmp/cert_import.sh

# Certificate synchronization
#- name: dse | synchronize public cert with other nodes in a cluster
#  synchronize:
#      mode: pull
#      src: /etc/dse/conf/{{ansible_hostname}}.crt
#      dest: /etc/dse/conf/{{ansible_hostname}}.crt
#  delegate_to: cassandra1

# Copy Cassandra configuration
- name: dse | copy cassandra.yml conf file
  template: src=cassandra.yaml.j2 dest=/etc/dse/cassandra/cassandra.yaml owner=cassandra
  notify: restart dse

# Copy cqlshrc
- name: dse | copy cqlshrc conf file
  template: src=cqlshrc.j2 dest=/root/.cassandra/cqlshrc owner=root


# Start Cassandra service
- name: dse | start service
  service: name=dse state=started enabled=yes

- name: pause to let dse start up completely
  pause: seconds=30
