---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

# Debian
- name: Install the DSE and required packages (will take a while...)
  apt: name={{ item }} state=installed update_cache=yes
  with_items: dse_packages
  when: ansible_os_family == 'Debian'

# Debian
- name: Install helper packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items: other_packages
  when: ansible_os_family == 'Debian'


# RedHat
- name: Install the DSE and required packages (will take a while...)
  yum: name={{ item }} state=installed
  with_items: dse_packages
  when: ansible_os_family == 'RedHat'
