---

# Debian
- name: Install Datastax Repository
  apt_repository: repo="deb https://piotr.wreczycki%40datastax.com:Datastax.8@debian.datastax.com/enterprise stable main" state=present
  when: ansible_os_family == 'Debian'

- name: Add Datastax key
  apt_key: url="https://debian.datastax.com/debian/repo_key" state=present
  when: ansible_os_family == 'Debian'

# RedHat
- name: Install Datastax Repository
  copy: src=datastax.repo dest=/etc/yum.repos.d/datastax.repo mode=0644
  when: ansible_os_family == 'RedHat'